[package]
name = "chippy-native"
version = "0.1.0"
edition = "2018"

[dependencies]
chippy = { path = "../../chippy" }
env_logger = "0.9.0"
eyre = "0.6.5"
log = "0.4.14"
pixels = "0.6.0"
winit = "0.25.0"
